### ISSUE TITLE
Failed to train using gpu

### ISSUE THREAD

**Issue by MENG2010** [sony/nnabla-examples#146]
a ModuleNotFoundError was thrown when performing the following commands:
```
cd cifar10-100-collection
python classification.py -n cifar100_resnet23
```

```
2020-05-02 06:43:17,572 [nnabla][INFO]: Initializing CPU extension...
2020-05-02 06:43:17,866 [nnabla][ERROR]: Extension `cudnn` does not exist.
Traceback (most recent call last):
  File "classification.py", line 158, in <module>
    train()
  File "classification.py", line 60, in train
    extension_module, device_id=args.device_id, type_config=args.type_config)
  File "/home/tester/anaconda3/envs/nnabla/lib/python3.7/site-packages/nnabla/ext_utils.py", line 97, in get_extension_context
    mod = import_extension_module(ext_name)
  File "/home/tester/anaconda3/envs/nnabla/lib/python3.7/site-packages/nnabla/ext_utils.py", line 50, in import_extension_module
    raise e
  File "/home/tester/anaconda3/envs/nnabla/lib/python3.7/site-packages/nnabla/ext_utils.py", line 46, in import_extension_module
    return importlib.import_module('.' + ext_name, 'nnabla_ext')
  File "/home/tester/anaconda3/envs/nnabla/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'nnabla_ext.cudnn'
```

**Comment by MENG2010** [comment]
Solved by install the package.
`pip install nnabla-ext-cuda101
`

**Comment by jorge190588** [comment]
I implemented the solution but I didn´t work for me.  Currently, I am looking for a solution.

**Comment by TomonobuTsujikawa** [comment]
@jorge190588 san,
This issue seems to be too old, and the current environment is completely different.
(For example, we don't support cuda10.1 anymore.)
So, I recommend that you file a new issue with the CUDA and nnabla software you have installed, and the errors you are encountering.
