### ISSUE TITLE
First order Motion Model: Voxceleb_trained_info.yaml could not be found

### ISSUE THREAD

**Issue by tjess78** [sony/nnabla-examples#318]
Hi,
I tried your colab for the first order motion model and stuck at "Image Animation using arbitrary source images" because of this error. Could you please fix this.
Thanks
tjess78

Traceback (most recent call last):
  File "animate.py", line 337, in <module>
    main()
  File "animate.py", line 333, in main
    animate(args)
  File "animate.py", line 113, in animate
    "https://nnabla.org/pretrained-models/nnabla-examples/GANs/first-order-model/voxceleb_trained_info.yaml")
  File "animate.py", line 51, in download_provided_file
    download(url, filepath, False)
  File "/usr/local/lib/python3.7/dist-packages/nnabla/utils/download.py", line 57, in download
    r = request.urlopen(url)
  File "/usr/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

**Comment by TomonobuTsujikawa** [comment]
Thank you for reporting.
Please let me handle this issue ASAP.

**Comment by TomonobuTsujikawa** [comment]
We're sorry for missing files.
Now you can download voxceleb_trained_info.yaml, and run colab demo correctly.

**Comment by TomonobuTsujikawa** [comment]
I think this issue already resolved, so please let me close.
Please let me know if you still have any problems.
