### ISSUE TITLE
run word_embedding.py error 

### ISSUE THREAD

**Issue by grb2015** [sony/nnabla-examples#34]
I just cloned   nnabla-examples  from github  and  run word_embedding.py as below:

[root@ word-embedding]# python word_embedding.py
2018-07-11 14:30:30,850 [nnabla][INFO]: Initializing CPU extension...
2018-07-11 14:30:34,554 [nnabla][INFO]: > /root/nnabla_data/ptb.train.txt already exists.
2018-07-11 14:30:34,554 [nnabla][INFO]: > If you have any issue when using this file, 
2018-07-11 14:30:34,554 [nnabla][INFO]: > manually remove the file and try download again.
2018-07-11 14:30:34,839 [nnabla][INFO]: Running in None
Traceback (most recent call last):
  File "word_embedding.py", line 408, in <module>
    main()
  File "word_embedding.py", line 310, in main
    args.context, device_id=args.device_id, type_config=args.type_config)
  File "/root/anaconda3/lib/python3.6/site-packages/nnabla/ext_utils.py", line 97, in get_extension_context
    mod = import_extension_module(ext_name)
  File "/root/anaconda3/lib/python3.6/site-packages/nnabla/ext_utils.py", line 46, in import_extension_module
    return importlib.import_module('.' + ext_name, 'nnabla_ext')
TypeError: must be str, not NoneType
[root@ word-embedding]#

**Comment by grb2015** [comment]
python word_embedding.py -c cpu          passed

**Comment by grb2015** [comment]
python word_embedding.py -c cpu          passed
