### ISSUE TITLE
Could find no file with path

### ISSUE THREAD

**Issue by heraldob** [sony/nnabla-examples#349]
when i run:

!python generate.py --model tecogan_model.h5 --input-dir-lr frames/input_video/ --output-dir results/user
!ffmpeg -i results/user/output_frame_%04d.png -r 24/1 -y user_video_hr.mp4

I get the following error:

2022-10-11 05:55:28,867 [nnabla][INFO]: Initializing CPU extension...
/content/nnabla-examples/utils
2022-10-11 05:55:29,335 [nnabla][ERROR]: Extension `cudnn` does not exist.
Traceback (most recent call last):
  File "generate.py", line 41, in <module>
    ctx = get_extension_context('cudnn')
  File "/usr/local/lib/python3.7/dist-packages/nnabla/ext_utils.py", line 97, in get_extension_context
    mod = import_extension_module(ext_name)
  File "/usr/local/lib/python3.7/dist-packages/nnabla/ext_utils.py", line 50, in import_extension_module
    raise e
  File "/usr/local/lib/python3.7/dist-packages/nnabla/ext_utils.py", line 46, in import_extension_module
    return importlib.import_module('.' + ext_name, 'nnabla_ext')
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/lib/python3.7/dist-packages/nnabla_ext/cudnn/__init__.py", line 19, in <module>
    import nnabla_ext.cuda
  File "/usr/local/lib/python3.7/dist-packages/nnabla_ext/cuda/__init__.py", line 131, in <module>
    load_shared_from_error(err)
  File "/usr/local/lib/python3.7/dist-packages/nnabla_ext/cuda/__init__.py", line 67, in load_shared_from_error
    raise err
  File "/usr/local/lib/python3.7/dist-packages/nnabla_ext/cuda/__init__.py", line 122, in <module>
    from .init import (
ImportError: libcudart.so.10.0: cannot open shared object file: No such file or directory
ffmpeg version 3.4.11-0ubuntu0.1 Copyright (c) 2000-2022 the FFmpeg developers
  built with gcc 7 (Ubuntu 7.5.0-3ubuntu1~18.04)
  configuration: --prefix=/usr --extra-version=0ubuntu0.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --enable-gpl --disable-stripping --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librubberband --enable-librsvg --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libopencv --enable-libx264 --enable-shared
  libavutil      55. 78.100 / 55. 78.100
  libavcodec     57.107.100 / 57.107.100
  libavformat    57. 83.100 / 57. 83.100
  libavdevice    57. 10.100 / 57. 10.100
  libavfilter     6.107.100 /  6.107.100
  libavresample   3.  7.  0 /  3.  7.  0
  libswscale      4.  8.100 /  4.  8.100
  libswresample   2.  9.100 /  2.  9.100
  libpostproc    54.  7.100 / 54.  7.100
[image2 @ 0x555654e34000] Could find no file with path 'results/user/output_frame_%04d.png' and index in the range 0-4
results/user/output_frame_%04d.png: No such file or directory

**Comment by TomonobuTsujikawa** [comment]
I think you use google colab.

> ImportError: libcudart.so.10.0: cannot open shared object file: No such file or directory

It said there is no cuda10.0 environment, this runtime seems to unsupport cuda10.0.
So, could you please change to use `nnabla-ext-cuda114` not `nnabla-ext-cuda100` as follows?

> !pip install nnabla-ext-cuda114
> !pip install ffmpeg
> !git clone https://github.com/sony/nnabla-examples.git
> %cd nnabla-examples/video-superresolution/tecogan
